(in-package :mu-cl-resources)

; Catalogs & Agent (publisher)
(define-resource catalog ()
  :class (s-prefix "dcat:Catalog")
  :properties `((:modified :string, (s-prefix "dct:modified"))
                (:description :string, (s-prefix "dct:description"))
                (:language :uri, (s-prefix "dct:language"))
                (:license :uri, (s-prefix "dct:license"))
                (:title :string, (s-prefix "dct:title"))
                (:issued :string, (s-prefix "dct:issued")))
  :has-one `((agent :via, (s-url "http://purl.org/dc/terms/publisher") :as "publisher"))
  :has-many `((dataset :via, (s-url "http://www.w3.org/ns/dcat#dataset") :as "datasets"))
  :resource-base (s-url "https://datatank.stad.gent/4/api/")
  :on-path "catalogs")

(define-resource agent ()
  :class (s-prefix "foaf:Agent")
  :properties `((:name :string, (s-prefix "foaf:name")))
  :has-one `((catalog :via, (s-url "http://purl.org/dc/terms/publisher") :inverse t :as "catalog"))
  :resource-base (s-url "http://data.vlaanderen.be/agents")
  :on-path "agents")



; Datasets
(define-resource dataset ()
  :class (s-prefix "dcat:Dataset")
  :properties `((:modified :string, (s-prefix "dct:modified"))
                (:description :string, (s-prefix "dct:description"))
                (:identifier :string, (s-prefix "dct:identifier"))
                (:title :string, (s-prefix "dct:title"))
                (:distribution :uri, (s-prefix "dcat:distribution"))
                (:keyword :string-set, (s-prefix "dcat:keyword"))
                (:theme :uri, (s-prefix "dcat:theme"))
                (:issued :string, (s-prefix "dct:issued")))
  :has-one `((dataset :via, (s-url "http://www.w3.org/ns/dcat#landingPage") :as "landing-page")
             (catalog :via, (s-url "http://www.w3.org/ns/dcat#dataset") :inverse t :as "catalog"))
  :has-many `((distribution :via ,(s-url "http://www.w3.org/ns/dcat#distribution") :as "distributions"))
  :resource-base (s-url "https://datatank.stad.gent/4/")
  :on-path "datasets")


; Distributions
(define-resource distribution ()
  :class (s-prefix "dcat:Distribution")
  :properties `((:description :string, (s-prefix "dct:description"))
                (:media-type :string, (s-prefix "dcat:mediaType"))
                (:title :string, (s-prefix "dct:title"))
                (:license :uri, (s-prefix "dct:license"))
                (:access-url :uri, (s-prefix "dcat:accessURL"))
                (:download-url :uri, (s-prefix "dcat:downloadURL"))
                (:issued :string, (s-prefix "dct:issued"))
                (:modified :string, (s-prefix "dct:modified")))
  :has-one `((dataset :via, (s-url "http://www.w3.org/ns/dcat#distribution") :inverse t :as "dataset"))
  :resource-base (s-url "https://datatank.stad.gent/4/bestuurenbeleid/")
  :on-path "distributions")
