(in-package :mu-cl-resources)

(add-prefix "rr" "http://www.w3.org/ns/r2rml#")
(add-prefix "rml" "http://semweb.mmlab.be/ns/rml#")
(add-prefix "ql" "http://semweb.mmlab.be/ns/ql#")
(add-prefix "schema" "http://schema.org/")
(add-prefix "org" "http://www.w3.org/ns/org#")
(add-prefix "xsd" "http://www.w3.org/2001/XMLSchema#")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "vcard" "http://www.w3.org/2006/vcard/ns#")
(add-prefix "oslo" "http://purl.org/oslo/ns/localgov#")
(add-prefix "rov" "http://www.w3.org/ns/regorg#")
(add-prefix "kbo" "http://data.kbodata.be/def#")
(add-prefix "locn" "http://www.w3.org/ns/locn#")
(add-prefix "foaf" "http://xmlns.com/foaf/0.1/")
(add-prefix "geo" "http://www.opengis.net/ont/geosparql#")
(add-prefix "db" "http://dbpedia.org/ontology/")
(add-prefix "xkos" "http://rdf-vocabulary.ddialliance.org/xkos#")
(add-prefix "geovl" "http://data.vlaanderen.be/ns/geo#")
(add-prefix "ext" "http://mu.semte.ch/vocabularies/ext/")
(add-prefix "adres" "http://data.vlaanderen.be/ns/adres#")
(add-prefix "dvl" "http://data.vlaanderen.be/ns/generiek#")
(add-prefix "dvlgeo" "http://data.vlaanderen.be/ns/geometrie#")
(add-prefix "lgdo" "http://linkedgeodata.org/ontology/")

(add-prefix "dcat" "http://www.w3.org/ns/dcat#")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "cc" "https://creativecommons.org/ns#")
(add-prefix "rdf" "http://www.w3.org/1999/02/22-rdf-syntax-ns#")
(add-prefix "rdfs" "http://www.w3.org/2000/01/rdf-schema#")
(add-prefix "owl" "http://www.w3.org/2002/07/owl#")
(add-prefix "mu" "http://mu.semte.ch/vocabularies/core/")
